name: "[delete] Feature Package(s)"
on:
  workflow_dispatch:
    inputs:
      feature:
        type: choice
        description: Which feature package(s) I delete?
        required: true
        default: '*'
        options:
        - '*'
        - 'dc-ccli'
        - 'dc-pkgx'

run-name: >-
  [delete] Feature Package: "${{ inputs.feature }}"
concurrency:
  group: ${{ github.workflow }}-${{ inputs.feature }}
  cancel-in-progress: false

jobs:
  deploy:
    name: '[delete] Feature Package(s)'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      feature: ${{ inputs.feature }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - if: ${{ inputs.feature == '*' }}
        id: delete-all
        name: 'Delete all Packages'
        shell: /usr/bin/bash --noprofile --norc -o errexit -o pipefail -o noclobber -o nounset -e {0}
        ## see: https://github.com/actions/github-script
        ## see: https://github.com/actions/delete-package-versions
        run: |
          printf '=== gh version\n'
          gh version

          readonly apiUrl='/users/${{ github.repository_owner }}/packages?package_type=container&per_page=100'
          printf '=== Get package list from "%s"\n' \
            "${apiUrl}"
          readonly packagesList=$(
            gh api \
              --method 'GET' \
              -H 'Accept: application/vnd.github+json' \
              -H 'X-GitHub-Api-Version: 2022-11-28' \
              "${apiUrl}" \
              --jq '.[].name' \
            || true
          )

          if [ -z "${packagesList}" ]; then
            echo '=== No packages found. Aborting ...'
            exit 0
          fi

          declare -ra packagesArray=( $(echo ${packagesList} | tr '\n' ' ') )

          printf '=== Found "%s" packages\n' \
                "${#packagesArray[@]}"

          for package in "${packagesArray[@]}"; do
            if ! [[ "${package}" =~ ^(dc-features)(\/.+)?$ ]]; then
              printf '=== Skip package: "%s" ... \n' \
                "${package}"
              continue
            fi
            packageUrlEncoded="$(echo -n "${package}" | sed 's#\/#\%2F#g')"
            printf '=== Delete package: "%s"\n' \
                "${package}"

            gh api \
              --method 'DELETE' \
              -H 'Accept: application/vnd.github+json' \
              -H 'X-GitHub-Api-Version: 2022-11-28' \
              "/users/${{ github.repository_owner }}/packages/container/${packageUrlEncoded}"
          done

      - if: ${{ inputs.feature != '*' }}
        name: 'Delete selected Package'
        id: delete-selected
        shell: /usr/bin/bash --noprofile --norc -o errexit -o pipefail -o noclobber -o nounset -e {0}
        run: |
          gh api \
            --method 'DELETE' \
            -H 'Accept: application/vnd.github+json' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            '/users/${{ github.repository_owner }}/packages/container/dc-features%2F${{ env.feature }}'